# Generated by Django 3.1.3 on 2020-11-13 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_productreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ('-date_added',)},
        ),
    ]
