# Generated by Django 3.1.3 on 2020-11-21 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20201113_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('base', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('tooltip', models.TextField(max_length=255)),
                ('ingredients', models.TextField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='flavour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flavours', to='store.flavour'),
        ),
    ]
