# Generated by Django 3.1.3 on 2020-11-21 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20201121_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flavour',
            name='product',
        ),
        migrations.AddField(
            model_name='flavour',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flavours', to='store.product'),
        ),
    ]
