# Generated by Django 3.1.3 on 2020-11-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20201121_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavour',
            name='eggs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flavour',
            name='gluten',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flavour',
            name='milk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flavour',
            name='nuts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flavour',
            name='oats',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flavour',
            name='peanuts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flavour',
            name='soya',
            field=models.BooleanField(default=False),
        ),
    ]
