# Generated by Django 3.1.3 on 2020-11-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20201125_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavour',
            name='wheat',
            field=models.BooleanField(default=False),
        ),
    ]
