# Generated by Django 3.1.3 on 2020-11-25 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_flavour_wheat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flavour',
            name='wheat',
        ),
    ]
