# Generated by Django 3.1.3 on 2021-01-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_remove_flavour_wheat'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sabores',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
