# Generated by Django 3.1.3 on 2021-01-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_product_sabores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('base', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('tooltip', models.TextField(max_length=255)),
                ('ingredients', models.TextField(max_length=255)),
                ('gluten', models.BooleanField(default=False)),
                ('eggs', models.BooleanField(default=False)),
                ('peanuts', models.BooleanField(default=False)),
                ('soya', models.BooleanField(default=False)),
                ('milk', models.BooleanField(default=False)),
                ('nuts', models.BooleanField(default=False)),
                ('oats', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Flavour',
        ),
        migrations.AddField(
            model_name='product',
            name='flavor',
            field=models.ManyToManyField(related_name='flavors', to='store.Flavor'),
        ),
    ]
