# Generated by Django 3.1.3 on 2021-02-08 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_auto_20210208_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='flavor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sabores',
        ),
        migrations.DeleteModel(
            name='Flavor',
        ),
    ]
