# Generated by Django 3.1.3 on 2021-02-18 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_cat_instagram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spoon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('num_available', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='spoon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spoons', to='store.spoon'),
        ),
    ]
