# Generated by Django 3.1.3 on 2021-02-19 19:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_spoon_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='spoon',
        ),
        migrations.AddField(
            model_name='spoon',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spoon',
            name='slug',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
