# Generated by Django 3.1.3 on 2021-02-24 21:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_productimage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='content',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
