# Generated by Django 3.1.3 on 2021-02-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_product_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='eggs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='gluten',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='milk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='nuts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='oats',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='peanuts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='soya',
            field=models.BooleanField(default=False),
        ),
    ]
