# Generated by Django 3.1.3 on 2020-11-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20201114_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
