# Generated by Django 3.1.3 on 2020-11-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20201120_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivered_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
