# Generated by Django 3.1.3 on 2021-01-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20201120_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='sabores',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
