# Generated by Django 3.1.3 on 2021-02-27 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_remove_orderitem_flavor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',)},
        ),
    ]
