# Generated by Django 3.1.3 on 2020-11-20 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_auto_20201120_0853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping',
            old_name='active',
            new_name='is_valid',
        ),
    ]
